apiVersion: v1
kind: Namespace
metadata:
  name: template-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-operator-manager
  namespace: template-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: template-operator-leader-election-role
  namespace: template-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: template-operator-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: template-operator-leader-election-rolebinding
  namespace: template-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: template-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: template-operator-manager
  namespace: template-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: template-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: template-operator-manager-role
subjects:
- kind: ServiceAccount
  name: template-operator-manager
  namespace: template-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    control-plane: template-operator
  name: template-operator-template-operator
  namespace: template-operator
spec:
  ports:
  - name: prometheus
    port: 8080
    protocol: TCP
  selector:
    control-plane: template-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: template-operator
  name: template-operator-controller-manager
  namespace: template-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: template-operator
  template:
    metadata:
      labels:
        control-plane: template-operator
    spec:
      containers:
      - args:
        - --metrics-addr=0.0.0.0:8080
        - --enable-leader-election
        - --sync-period=20s
        image: flanksource/template-operator:dev
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 130Mi
          requests:
            cpu: 100m
            memory: 120Mi
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=2
        image: bitnami/kube-rbac-proxy:v0.12.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      serviceAccount: template-operator-manager
      terminationGracePeriodSeconds: 10
