apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: template-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: template-operator
spec:
  selector:
    matchLabels:
      control-plane: template-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: template-operator
    spec:
      containers:
        - image: controller:latest
          args:
            - --enable-leader-election
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
      serviceAccount: template-operator-manager
