apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: template-operator
spec:
  selector:
    matchLabels:
      control-plane: template-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: template-operator
    spec:
      containers:
        - image: controller:latest
          args:
            - "--metrics-addr=0.0.0.0:8080"
            - "--enable-leader-election"
            - "--sync-period=20s"
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 130Mi
            requests:
              cpu: 100m
              memory: 120Mi
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=10"
          ports:
          - containerPort: 8443
            name: https
      terminationGracePeriodSeconds: 10
      serviceAccount: template-operator-manager
---
apiVersion: v1
kind: Service
metadata:
  name: template-operator
  namespace: platform-system
  annotations:
    prometheus.io/scrape: "true"
  labels:
    control-plane: template-operator
spec:
  selector:
    control-plane: template-operator
  ports:
    - name: prometheus
      protocol: TCP
      port: 8080