# permissions for end users to edit templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-editor-role
rules:
- apiGroups:
  - templating.flanksource.com.flanksource.com
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templating.flanksource.com.flanksource.com
  resources:
  - templates/status
  verbs:
  - get
