apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: git-repository
spec:
  source:
    gitRepository:
      namespace: default
      name: template-operator-dashboards
      glob: "/grafana/dashboards/*.json"
  resources:
    - apiVersion: integreatly.org/v1alpha1
      kind: GrafanaDashboard
      metadata:
        name: "{{ .filename | filepath.Base }}"
        namespace: monitoring
        labels:
          app: grafana
      spec:
        json:  "{{ .content }}"