apiVersion: v1
kind: Namespace
metadata:
  name: test-secrets
  labels:
    template-operator-test: secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: template-default-secrets
  namespace: test-secrets
  labels:
    secrets.flanksource.com/label: defaults
stringData:
  domain: 127.0.0.1.nip.io
  foo: bar
type: Opaque
---
apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: copy-secret
spec:
  source:
    apiVersion: v1
    kind: Secret
    namespaceSelector:
      matchLabels:
        template-operator-test: secrets
    labelSelector:
      matchLabels:
        secrets.flanksource.com/label: defaults
  copyToNamespaces:
    namespaces:
      - minio
      - monitoring
      - template-operator
      - quack