apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.example.flanksource.com
spec:
  group: example.flanksource.com
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      description: Schema validation for the App Crds
      type: object
      properties:
        spec:
          type: object
---
apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: app-example
spec:
  source:
    apiVersion: apps.example.flanksource.com/v1
    kind: App
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{.metadata.name}}"
        namespace: "{{.metadata.namespace}}"
        labels:
          app: "{{.metadata.name}}"
      spec:
        replicas: "{{.spec.replicas | default 1}}"
        selector:
          matchLabels:
            app: "{{.metadata.name}}"
        template:
          metadata:
            labels:
              app: "{{.metadata.name}}"
          spec:
            containers:
            - name: web
              image: "{{.spec.image}}"
              ports:
              - containerPort: 80
    - when: "{{.spec.exposeService}}"
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{.metadata.name}}"
        namespace: "{{.metadata.namespace}}"
      spec:
        selector:
          app: "{{.metadata.name}}"
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80